version: '2'
services:
  postfix:
    image: juanluisbaptiste/postfix:latest@sha256:93b58de5b5716295151acbffbfc08e80409c01e0ef5cf7763bc30dc49fc5c39f
    expose:
    - "25"
    env_file:
      - .env
    restart: always
    volumes:
     - "/etc/localtime:/etc/localtime:ro"
